version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - echo Installing Node 16...
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
      - echo Installing Npm...
      - npm install -g npm
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm instal
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - ls
      
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build