name: DEV Deploy S3

on:
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git Branch
      uses: actions/checkout@v2
      with:
        ref: 'prod'

# Sync to S3
    # - name: S3 Sync
    #   uses: ItsKarma/aws-cli@v1.70.0
    #   with:
    #     args: s3 cp ./signalstickermaker/build s3://prod.signalstickermaker.com --recursive

    - name: S3 Sync
      run: aws s3 cp ./build s3://portfolionghoiwa2021 --recursive
      # working-directory: ./apiService/functions/uploadSignal

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "ap-southeast-1"
